controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    use_sim_time: true

    # register controllers to controller manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    fixed_cart:
      type: position_controllers/JointGroupPositionController

    fixed_joint:
      type: position_controllers/JointGroupPositionController

    passive_joint:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    joints:
      - slider

fixed_cart:
  ros__parameters:
    joints:
      - slider

fixed_joint:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

passive_joint:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
