controller_manager:
  ros__parameters:
    update_rate: 100 #Hz
    use_sim_time: true

    # register controllers to controller manager
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cart_effort_controller:
      type: effort_controllers/JointGroupEffortController

    cart_fixed:
      type: position_controllers/JointGroupPositionController

    pendulums_passive:
      type: effort_controllers/JointGroupEffortController

    all_fixed:
      type: position_controllers/JointGroupPositionController

cart_effort_controller:
  ros__parameters:
    joints:
      - slider

cart_fixed:
  ros__parameters:
    joints:
      - slider

pendulums_passive:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3

all_fixed:
  ros__parameters:
    joints:
      - slider
      - joint1
      - joint2
      - joint3
